Add Counter By Redux
jiks-dev/toy-init-react pull request #4
Opened 2022-04-03 16:19 UTC by rd-dhyoo

# Description
- 리덕스를 이용한 카운터 프로그램

2022-04-03 23:24 UTC, karriz-dev requested changes
.vscode/ 을 .gitignore에 등록해주세요

2022-04-03 23:25 UTC, karriz-dev commented
redux 사용법에 대해서 익혔다면 `redux-actions` 라는 라이브러리로 가독성을 높혀보세요.

2022-04-05 12:56 UTC, rd-dhyoo commented
> 

다음 PR에 처리 예정입니다~

2022-04-05 13:06 UTC, rd-dhyoo commented
> .vscode/ 을 .gitignore에 등록해주세요

https://velog.io/@bky373/Git-gitignore%EC%97%90-.vscode-%EC%B6%94%EA%B0%80%ED%95%B4%EB%8F%84-.vscode%EA%B0%80-%EC%82%AC%EB%9D%BC%EC%A7%80%EC%A7%80-%EC%95%8A%EC%9D%84-%EB%95%8C

2022-04-07 22:58 UTC, merged